config/routes.rb
Rails.application.routes.draw do
  resources :likes
  resources :videos
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/videos', to: 'welcome#index'
  post '/videos/:id/like', to: 'videos#like'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :video

  def like(user, video)
    row = Like.find_or_initialize_by(user: user, video: video)
    row.save
  end
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord
  # users.password_hash in the database is a :string
  include BCrypt
  has_many :videos
  has_many :likes

  validates :name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true

  # users.password_hash in the database is a :string

  def password
    @password ||= Password.new(password_hash) unless password_hash.nil?
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end


end

app/models/video.rb
class Video < ApplicationRecord
  has_many :likes


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method def logged_in?
    session[:user_id]
  end

  helper_method def current_user
    @current_user ||= User.find(session[:user_id]) if logged_in?
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:show, :edit, :update, :destroy]

  # GET /likes
  # GET /likes.json
  def index
    @likes = Like.all
  end

  def go_home
    redirect_to root_path unless logged_in?
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit
  end

  def create_like
    puts("\n\n\n\n")
    puts(params)
    @new_like.create
  end

  # POST /likes
  # POST /likes.json
  def create
    puts(params)
    @like = Like.new

    respond_to do |format|
      if @like.save
        format.html { redirect_to @like, notice: 'Like was successfully created.' }
        format.json { render :show, status: :created, location: @like }
      else
        format.html { render :new }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /likes/1
  # PATCH/PUT /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to @like, notice: 'Like was successfully updated.' }
        format.json { render :show, status: :ok, location: @like }
      else
        format.html { render :edit }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html { redirect_to likes_url, notice: 'Like was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.password == params[:password]
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to '/login'
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @video = Video.new
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.password = user_params[:password]

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
    reset_session
  end

  def like
    redirect_to root_path unless logged_in?
    current_user.like(@video)
    redirect_to @video
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :watchtime)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy, :like]

  # helper_method def empty?
  #   if Video.all > 0
  #     return false
  #   end
  #   return true
  # end

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end


  def getname
    return @video.name
  end
  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  def edit
  end

  # POST /videos/1/like
  def like
    redirect_to root unless logged_in?
    Like.create(user: current_user, video: @video)
    redirect_to @video
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :URL)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @video = Video.new
    @videos = Video.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark mb-4" style="background-color: #122722;">
  <div class="container" style = "color: #122bb2">
    <center><h1 style = "color:red;"><%= link_to 'Ad Watcher', root_path, class: 'navbar-brand' %>
</h1></center>
    <div id="navbar_content" class="collapse navbar-collapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><%= link_to 'Videos', '/videos', class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Best Videos', '/likes', class: 'nav-link' %></li>
        <% if logged_in? %>
        <%# Only display the current user's name, friend requests, and log out links if a user is logged in %>
          <li class="nav-item"><%= link_to current_user.name, "/users/#{current_user.id}", class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to "Log out", '/logout', method: :delete, class: 'nav-link' %></li>
        <%# Only display the sign up and log in links if no user is logged in %>
        <% else %>
          <li class="nav-item"><%= link_to "Sign up", '/users/new', class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to "Log in", '/login', class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


<!-- <nav class="navbar navbar-expand-lg navbar-dark mb-4" style="background-color: #4267b2;">
  <div class="container">
    <%= link_to 'Ad Watcher', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_content" aria-controls="navbar_content" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar_content" class="collapse navbar-collapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><%= link_to 'Videos', '/videos', class: 'nav-link' %></li>
        <% if logged_in? %>
        <%# Only display the current user's name, friend requests, and log out links if a user is logged in %>
          <li class="nav-item"><%= link_to current_user.name, "/users/#{current_user.id}", class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to "Likes", '/likes', class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to "Log out", '/logout', method: :delete, class: 'nav-link' %></li>
        <%# Only display the sign up and log in links if no user is logged in %>
        <% else %>
          <li class="nav-item"><%= link_to "Sign up", '/users/new', class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to "Log in", '/login', class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdWatcher</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color:#00BFFF;">
    <%= render 'layouts/nav' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/likes/_form.html.erb
<%= form_for(like) do |f| %>
  <% if like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
      <% like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :video_id %>
    <%= f.text_field :video_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/likes/edit.html.erb
<h1>Editing Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

app/views/likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Likes</h1>

<table>
  <thead>
    <tr>
      <th>Video Title</th>
      <th>Watch it!</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% puts @likes.size %>
    <%@videos = Video.all.sort_by { |video| -video.likes.count }%>
<%puts(@videos)%>
    <% @videos.each do |vid| %>
      <tr>

        <td><%= vid.title %></td>
        <td><%= link_to 'Show', vid %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/likes/new.html.erb
<h1>New Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Back', likes_path %>

app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @like.user %>
</p>

<p>
  <strong>Video:</strong>
  <%= @like.video %>
</p>

<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_area :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_area :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :watchtime %>
    <%= f.text_field :watchtime %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Add your watch time!</h1>
<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :watchtime %>
    <%= f.text_field :watchtime %>
  </div>
<div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password hash</th>
      <th>Watchtime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_hash %></td>
        <td><%= user.watchtime %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Watchtime:</strong>
  <%= @user.watchtime %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/videos/_form.html.erb
<%= form_for(video) do |f| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :URL %>
    <%= f.text_field :URL %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/_video.html.erb
<% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>

        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <br>
      </tr>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>

<p>
  <iframe width="560" height="315" src= "https://www.youtube.com/embed/<%= @video.URL %>"frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>
</p>

<%if logged_in?%>
<%= link_to 'Like this video', "/videos/#{@video.id}/like", method: :post%>
<%end%>
<%= link_to 'Back', videos_path %>

app/views/welcome/index.html.erb
<% if logged_in? %>
  <div class="row">
    <div class="col-lg-6 offset-lg-3">
      <%= render 'videos/form', video: @video %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-lg-6 offset-lg-3">
      <% if @videos.empty? %>
        <p class="text-center">There aren't any videos yet, you should upload one!</p>
      <% else %>
        <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= video.URL %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <br>
      </tr>
    <% end %>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-lg-6 offset-lg-3">
      <h1>Welcome to Ad Watcher!</h1>
      <p>Sign up or log in to get started!</p>
      <p>So here's how this works. You log in and can watch any videos you want. After you watch a video, update your profile to add your watchtime. You can like any videos you watch as many times as you like, and you can access a sorted view of these videos. You can also upload any video from youtube! Just take the URL and delete "https://www.youtube.com/watch?v=" </p>
    </div>
  </div>
<% end %>